/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c ClientDBus -p clientdbus.h:clientdbus.cpp org.opensuse.oneclickinstaller.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CLIENTDBUS_H
#define CLIENTDBUS_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QDBusAbstractInterface>
#include <QtDBus/QDBusPendingReply>

/*
 * Proxy class for interface org.opensuse.oneclickinstaller
 */
class ClientDBus: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    {
        return "org.opensuse.oneclickinstaller";
    }

public:
    ClientDBus( const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0 );

    ~ClientDBus();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> KillBackend()
    {
        QList< QVariant > argumentList;
        return asyncCallWithArgumentList( QLatin1String( "KillBackend" ), argumentList );
    }

Q_SIGNALS: // SIGNALS
};

namespace org {
  namespace opensuse {
    typedef ::ClientDBus oneclickinstaller;
  }
}
#endif
