/*
* This file was generated by qdbusxml2cpp version 0.7
* Command line was: qdbusxml2cpp -v -c DBusAdaptor -a dbusadaptor.h:dbusadaptor.cpp org.opensuse.oneclickinstaller.xml
*
* qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
*
* This is an auto-generated file.
* This file may have been hand-edited. Look for HAND-EDIT comments
* before re-generating it.
*/

#ifndef DBUSADAPTOR_H
#define DBUSADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template< class T > class QList;
template< class Key, class Value > class QMap;
class QString;
class QStringList;
class QVariant;

/*
* Adaptor class for interface org.opensuse.oneclickinstaller
*/
class DBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO( "D-Bus Interface", "org.opensuse.oneclickinstaller" )
    Q_CLASSINFO( "D-Bus Introspection", ""
" <interface name=\"org.opensuse.oneclickinstaller\">\n"
" <method name=\"KillBackend\"/>\n"
" </interface>\n"
        "" )
public:
    DBusAdaptor( QObject *parent );
    virtual ~DBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void KillBackend();
Q_SIGNALS: // SIGNALS
};

#endif